# Generated by Django 4.0.4 on 2022-04-25 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Nickname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('encryption', models.BooleanField(choices=[(False, 'Claro'), (True, 'Criptografado')])),
                ('network', models.CharField(choices=[(1, 'Comando'), (2, 'Operações'), (3, 'Logística')], max_length=1)),
                ('environment', models.CharField(choices=[(1, 'Rádio'), (2, 'Telefone'), (3, 'Digital'), (4, 'Mensageiro')], max_length=1)),
                ('precedence', models.CharField(choices=[(1, 'Urgentíssima'), (2, 'Urgente'), (3, 'Preferencial'), (4, 'Rotina')], max_length=1)),
                ('confidentiality', models.CharField(choices=[(1, 'Ultra-Secreto'), (2, 'Secreto'), (3, 'Confidencial'), (4, 'Reservado'), (5, 'Ostensivo')], max_length=1)),
                ('receiver_nickname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.nickname')),
                ('receiver_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.organization')),
                ('sender_nickname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.nickname')),
                ('sender_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.organization')),
            ],
        ),
    ]
